# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Publish Npm Package

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Get checkout
      - uses: actions/checkout@v3

      # Install Node js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.10.0'

      # Install Dependencies
      - run: npm ci

      # Npm Run Test
      - run: npm run test:all

      # Npm run Build
      - run: npm run build
