# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Testing Code & Build App

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      # Get checkout
      - uses: actions/checkout@v3

      # Install Node js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.10.0'

      # Install Dependencies
      - run: npm ci

      # Npm Run Test
      - run: npm run test:all

      # Build application
      - run: npm run build
